### ISSUE TITLE
How to use lighthouse-layer?

### ISSUE THREAD

**Issue by EXPEpaher** [erezrokah/lighthouse-layer#21]
Hi, your project seems very useful for my usecase. My aws lambda function runs lighthouse audits, its taking too long to complete. Not sure whats the issue, I would like to try your lighthouse-layer, please can you share the instructions, its a little unclear to me.

**Comment by EXPEpaher** [comment]
Well, I was able to create a lambda layer,
`yarn run v1.17.3
$ serverless deploy
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Creating Stack...
Serverless: Checking Stack create progress...
........
Serverless: Stack create finished...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service lighthouse.zip file to S3 (120.59 MB)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
......
Serverless: Stack update finished...
Service Information
service: lighthouse-layer
stage: dev
region: us-east-1
stack: lighthouse-layer-dev
resources: 3
api keys:
  None
endpoints:
  None
functions:
  None
layers:
  lighthouse: arn:aws:lambda:us-east-1:408096535527:layer:lighthouse:1
Serverless: Run the "serverless" command to setup monitoring, troubleshooting and testing.
✨  Done in 523.35s.
`

Now I am running into this issue,
`Function code combined with layers exceeds the maximum allowed size of 262144000 bytes. The actual size is 303029591 bytes.`


My aws lambda zip file is 7.75 MB, I have used `npm install --production` to only zip prod dependencies and skip devDependencies to keep zip file small. 

`A function can use up to 5 layers at a time. The total unzipped size of the function and all layers can't exceed the unzipped deployment package size limit of 250 MB. For more information, see AWS Lambda Limits.`


So it seems that unzipped (lambda + layer) is exceeding 250MB in my case, did you experience any issues like this while using the lighthouse-layer? 

Looks like lighthouse.zip file size is 120.59 MB based on the console logs (pasted above). Is there anything we can do to reduce the size of the lighthouse-layer further?

**Comment by erezrokah** [comment]
You could try using https://github.com/alixaxel/chrome-aws-lambda directly. I think it uses compressed versions of Chromium and decompress it on demand.

**Comment by EXPEpaher** [comment]
Yes, I tried to use it directly, it worked, however, I am trying to solve a different issue that it didn't solve. 

My issue is that the lighthouse audit does not complete within 15mins, I have selected performance only in the categories. It completes for a very lightweight page, but not for the page that I wanted to test.

I have posted that issue here,
https://github.com/erezrokah/lighthouse-layer/issues/21

I wanted to give lighthouse-layer a try thinking it might solve the timeout issue I am seeing since it uses an uncompressed chromium binary.

**Comment by erezrokah** [comment]
It only saves the decompressing time (you could actually add some logs to measure it), but in your case you might need to increase the memory of your lambda to get more CPU power.
This won't help if the site you're testing has high latency though.

**Comment by EXPEpaher** [comment]
Agree, it will only save some decompression time. This is the lambda configuration,

```
name: new-aws-lambda
nodejs10.x
15mins timesout
3008MB
60.3MB zip file size
us-east-1 

"lighthouse": "4.3.1",
"chrome-aws-lambda": "2.1.1"
"chrome-launcher": "0.13.0"
"puppeteer-core": "2.1.1"
```

The old lambda that runs on 8.10 and completes in less than 2mins has this configuration,
`name: old-aws-lambda
nodejs8.10
2mins timeout
2048MB
61.5MB zip file size
us-west-2

"lighthouse": "4.3.1",
"@serverless-chrome/lambda": "1.0.0-55"`


Weird thing is that the same URL completes LH audit  in less than 2mins on the old lambda and doesn't complete even in 15mins on the new lambda. 

I am trying to narrow down on the differences and eliminating them one by one to understand why the new lambda is so slow.

**Comment by erezrokah** [comment]
Not sure, but maybe you should update your `lighthouse` to the latest version and stream the process logs.
I'm closing this issue as it is unrelated to the layer.
