### ISSUE TITLE
Nodejs 12.x runtime?

### ISSUE THREAD

**Issue by ysb** [erezrokah/lighthouse-layer#43]
Hi,
Is the package compatible with nodejs 12.x runtime?

**Comment by asendia** [comment]
Hi @ysb, I have tested it and it works with nodejs 12.x runntime.
I modified the `serverless.yml` to use `nodejs12.x` runtime though, not sure if that's needed or not.

**Comment by ysb** [comment]
Thanks @asendia 👍
